
import { Product } from './types';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: '1',
    slug: 'sucata-toyota-corolla-2015-inteira',
    sku: 'SUC-COR-15',
    title: 'Sucata Toyota Corolla 2015 para Peças',
    category: 'Sucata Veículo',
    brand: 'Toyota',
    model: 'Corolla',
    yearFrom: 2014,
    yearTo: 2016,
    condition: 'Usado',
    description: 'Sucata inteira para retirada de peças. Motor, câmbio e suspensão em ótimo estado.',
    compatibility: ['Toyota Corolla 2014-2017'],
    priceLabel: 'Sob consulta',
    images: ['https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&q=80&w=800'],
    status: 'available',
    createdAt: new Date().toISOString()
  },
  {
    id: 'bmw-x1-18',
    slug: 'sucata-bmw-x1-2018-para-pecas',
    sku: 'SUC-BMX1-18',
    title: 'Sucata BMW X1 2018 para Peças',
    category: 'Sucata Veículo',
    brand: 'BMW',
    model: 'X1',
    yearFrom: 2017,
    yearTo: 2019,
    condition: 'Usado',
    description: 'Sucata inteira para retirada de peças. Motor, câmbio e suspensão em ótimo estado.',
    compatibility: ['BMW X1 F48'],
    priceLabel: 'Sob consulta',
    images: ['https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&q=80&w=800'],
    status: 'available',
    createdAt: new Date().toISOString()
  },
  {
    id: 'merc-c180-17',
    slug: 'sucata-mercedes-benz-c180-2017-para-pecas',
    sku: 'SUC-MBC180-17',
    title: 'Sucata Mercedes-Benz C180 2017 para Peças',
    category: 'Sucata Veículo',
    brand: 'Mercedes-Benz',
    model: 'C180',
    yearFrom: 2016,
    yearTo: 2018,
    condition: 'Usado',
    description: 'Sucata inteira para retirada de peças. Motor, câmbio e suspensão em ótimo estado.',
    compatibility: ['Mercedes C-Class W205'],
    priceLabel: 'Sob consulta',
    images: ['https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&q=80&w=800'],
    status: 'available',
    createdAt: new Date().toISOString()
  },
  {
    id: 'audi-q5-19',
    slug: 'sucata-audi-q5-2019-para-pecas',
    sku: 'SUC-AUQ5-19',
    title: 'Sucata Audi Q5 2019 para Peças',
    category: 'Sucata Veículo',
    brand: 'Audi',
    model: 'Q5',
    yearFrom: 2018,
    yearTo: 2019,
    condition: 'Usado',
    description: 'Sucata inteira para retirada de peças. Motor, câmbio e suspensão em ótimo estado.',
    compatibility: ['Audi Q5 FY'],
    priceLabel: 'Sob consulta',
    images: ['https://images.unsplash.com/photo-1542282088-fe8426682e8f?auto=format&fit=crop&q=80&w=800'],
    status: 'available',
    createdAt: new Date().toISOString()
  },
  {
    id: 'volvo-xc60-20',
    slug: 'sucata-volvo-xc60-2020-para-pecas',
    sku: 'SUC-VXC60-20',
    title: 'Sucata Volvo XC60 2020 para Peças',
    category: 'Sucata Veículo',
    brand: 'Volvo',
    model: 'XC60',
    yearFrom: 2019,
    yearTo: 2020,
    condition: 'Usado',
    description: 'Sucata inteira para retirada de peças. Motor, câmbio e suspensão em ótimo estado.',
    compatibility: ['Volvo XC60 II'],
    priceLabel: 'Sob consulta',
    images: ['https://images.unsplash.com/photo-1519245659620-e859806a8d3b?auto=format&fit=crop&q=80&w=800'],
    status: 'available',
    createdAt: new Date().toISOString()
  },
  {
    id: 'hilux-16',
    slug: 'sucata-toyota-hilux-2016-para-pecas',
    sku: 'SUC-HLX-16',
    title: 'Sucata Toyota Hilux 2016 para Peças',
    category: 'Sucata Veículo',
    brand: 'Toyota',
    model: 'Hilux',
    yearFrom: 2015,
    yearTo: 2017,
    condition: 'Usado',
    description: 'Sucata inteira para retirada de peças. Motor, câmbio e suspensão em ótimo estado.',
    compatibility: ['Toyota Hilux 2016-2020'],
    priceLabel: 'Sob consulta',
    images: ['https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&q=80&w=800'],
    status: 'available',
    createdAt: new Date().toISOString()
  },
  {
    id: 'pajero-15',
    slug: 'sucata-mitsubishi-pajero-2015-para-pecas',
    sku: 'SUC-PAJ-15',
    title: 'Sucata Mitsubishi Pajero 2015 para Peças',
    category: 'Sucata Veículo',
    brand: 'Mitsubishi',
    model: 'Pajero',
    yearFrom: 2014,
    yearTo: 2016,
    condition: 'Usado',
    description: 'Sucata inteira para retirada de peças. Motor, câmbio e suspensão em ótimo estado.',
    compatibility: ['Mitsubishi Pajero Full / Dakar'],
    priceLabel: 'Sob consulta',
    images: ['https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&q=80&w=800'],
    status: 'available',
    createdAt: new Date().toISOString()
  },
  {
    id: 'discovery-18',
    slug: 'sucata-land-rover-discovery-sport-2018-para-pecas',
    sku: 'SUC-LRDSP-18',
    title: 'Sucata Land Rover Discovery Sport 2018 para Peças',
    category: 'Sucata Veículo',
    brand: 'Land Rover',
    model: 'Discovery Sport',
    yearFrom: 2017,
    yearTo: 2019,
    condition: 'Usado',
    description: 'Sucata inteira para retirada de peças. Motor, câmbio e suspensão em ótimo estado.',
    compatibility: ['Land Rover Discovery Sport L550'],
    priceLabel: 'Sob consulta',
    images: ['https://images.unsplash.com/photo-1506521781263-d8422e82f27a?auto=format&fit=crop&q=80&w=800'],
    status: 'available',
    createdAt: new Date().toISOString()
  },
  {
    id: 'compass-21',
    slug: 'sucata-jeep-compass-2021-para-pecas',
    sku: 'SUC-COMP-21',
    title: 'Sucata Jeep Compass 2021 para Peças',
    category: 'Sucata Veículo',
    brand: 'Jeep',
    model: 'Compass',
    yearFrom: 2020,
    yearTo: 2021,
    condition: 'Usado',
    description: 'Sucata inteira para retirada de peças. Motor, câmbio e suspensão em ótimo estado.',
    compatibility: ['Jeep Compass 2017-2022'],
    priceLabel: 'Sob consulta',
    images: ['https://images.unsplash.com/photo-1539727366521-03993a4087e5?auto=format&fit=crop&q=80&w=800'],
    status: 'available',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ranger-17',
    slug: 'sucata-ford-ranger-2017-para-pecas',
    sku: 'SUC-RAN-17',
    title: 'Sucata Ford Ranger 2017 para Peças',
    category: 'Sucata Veículo',
    brand: 'Ford',
    model: 'Ranger',
    yearFrom: 2016,
    yearTo: 2018,
    condition: 'Usado',
    description: 'Sucata inteira para retirada de peças. Motor, câmbio e suspensão em ótimo estado.',
    compatibility: ['Ford Ranger 2012-2019'],
    priceLabel: 'Sob consulta',
    images: ['https://images.unsplash.com/photo-1620324835639-669527581559?auto=format&fit=crop&q=80&w=800'],
    status: 'available',
    createdAt: new Date().toISOString()
  },
  {
    id: 'tracker-22',
    slug: 'sucata-chevrolet-tracker-2022-para-pecas',
    sku: 'SUC-TRK-22',
    title: 'Sucata Chevrolet Tracker 2022 para Peças',
    category: 'Sucata Veículo',
    brand: 'Chevrolet',
    model: 'Tracker',
    yearFrom: 2021,
    yearTo: 2022,
    condition: 'Usado',
    description: 'Sucata inteira para retirada de peças. Motor, câmbio e suspensão em ótimo estado.',
    compatibility: ['Chevrolet Tracker 2020-2023'],
    priceLabel: 'Sob consulta',
    images: ['https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&q=80&w=800'],
    status: 'available',
    createdAt: new Date().toISOString()
  }
];

export const CATEGORIES = ['Sucata Veículo', 'Sucata Caminhões'];
export const BRANDS = [
  'Audi', 
  'BMW', 
  'Chevrolet', 
  'Fiat', 
  'Ford', 
  'Honda', 
  'Hyundai',
  'Iveco',
  'Jeep', 
  'Land Rover', 
  'Mercedes-Benz', 
  'Mitsubishi', 
  'Scania', 
  'Toyota', 
  'Volkswagen', 
  'Volvo'
];
